'use client';

import React, { useState, useCallback } from 'react';
import { FileText, Download, Edit3, ChevronDown, CheckCircle2, AlertCircle, XCircle, Shield, Info } from 'lucide-react';
import { DEMO_PRODUCTS, type ProductAnalysis, type Finding, type Declaration } from '@/lib/mockData';

function StatusBadge({ status }: { status: 'PASS' | 'REVIEW' | 'FLAG' }) {
  if (status === 'PASS')
    return (
      <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-pass/10 text-pass text-xs font-semibold">
        <CheckCircle2 size={10} /> PASS
      </span>
    );
  if (status === 'REVIEW')
    return (
      <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-review/10 text-review text-xs font-semibold">
        <AlertCircle size={10} /> REVIEW
      </span>
    );
  return (
    <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-flag/10 text-flag text-xs font-semibold">
      <XCircle size={10} /> FLAG
    </span>
  );
}

function ProductSelector({ selected, onChange }: { selected: ProductAnalysis; onChange: (p: ProductAnalysis) => void }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="relative">
      <button
        onClick={() => setOpen((v) => !v)}
        className="flex items-center gap-2 px-4 py-2.5 rounded-xl border border-border bg-card hover:bg-muted transition-all text-sm font-medium text-navy"
      >
        <span>{selected.name}</span>
        <ChevronDown size={14} className={`transition-transform ${open ? 'rotate-180' : ''}`} />
      </button>
      {open && (
        <div className="absolute top-full left-0 mt-1 z-20 bg-card border border-border rounded-xl shadow-lg overflow-hidden min-w-[220px]">
          {DEMO_PRODUCTS.map((p) => (
            <button
              key={p.id}
              onClick={() => { onChange(p); setOpen(false); }}
              className={`w-full flex items-center justify-between px-4 py-3 text-sm hover:bg-muted transition-all ${selected.id === p.id ? 'bg-accent/5 text-accent font-semibold' : 'text-foreground'}`}
            >
              <span>{p.name}</span>
              <span className="text-xs text-muted-foreground">Score {p.qualityScore}</span>
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

function generateReportText(product: ProductAnalysis): string {
  const lines: string[] = [
    'LABELGUARD AI — COMPLIANCE SCREENING REPORT',
    '='.repeat(50),
    '',
    `Product: ${product.name}`,
    `Category: ${product.category}`,
    `Analyzed: ${product.analyzedAt}`,
    `Compliance Screening Score: ${product.qualityScore} / 100`,
    '',
    'SCORE BREAKDOWN',
    '-'.repeat(30),
    `Mandatory declarations:    ${product.scoreBreakdown.mandatoryDeclarations}`,
    `Readability:               ${product.scoreBreakdown.readability}`,
    `Extraction confidence:     ${product.scoreBreakdown.extractionConfidence}`,
    `Placement / visibility:    ${product.scoreBreakdown.placementVisibility}`,
    `Label consistency:         ${product.scoreBreakdown.labelConsistency}`,
    '',
    'SUMMARY OF FINDINGS',
    '-'.repeat(30),
    `PASS:   ${product.passCount}`,
    `REVIEW: ${product.reviewCount}`,
    `FLAG:   ${product.flagCount}`,
    '',
    'DECLARATIONS',
    '-'.repeat(30),
    ...product.declarations.map(
      (d) => `[${d.status}] ${d.field}: ${d.extractedText || d.value} (Confidence: ${d.confidence}%, Readability: ${d.readabilityPx}px)`
    ),
    '',
    'FINDINGS & EVIDENCE',
    '-'.repeat(30),
    ...product.findings.map(
      (f) =>
        `[${f.severity}] ${f.title}\n  Check: ${f.ruleCheck}\n  Detected: ${f.detectedText}\n  Confidence: ${f.confidence}%\n  Evidence: ${f.evidenceRegion}\n  Explanation: ${f.explanation}\n  Recommendation: ${f.recommendation}\n`
    ),
    '',
    'DISCLAIMER',
    '-'.repeat(30),
    'This report is generated by LabelGuard AI and is intended for informational purposes only.',
    'It does not constitute legal certification or official compliance verification.',
    'All findings are AI-assisted and require manual verification by a qualified inspector.',
    'AI-assisted screening — not an official legal certification.',
    '',
    `Generated: ${new Date().toUTCString()}`,
  ];
  return lines.join('\n');
}

function exportText(product: ProductAnalysis) {
  const text = generateReportText(product);
  const blob = new Blob([text], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `labelguard-report-${product.id}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

function exportPDF(product: ProductAnalysis) {
  const text = generateReportText(product);
  const win = window.open('', '_blank');
  if (!win) return;
  win.document.write(`
    <html><head><title>LabelGuard Report — ${product.name}</title>
    <style>
      body { font-family: monospace; font-size: 12px; padding: 32px; color: #1e293b; white-space: pre-wrap; }
      h1 { font-size: 16px; margin-bottom: 8px; }
    </style></head>
    <body>${text.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</body></html>
  `);
  win.document.close();
  win.focus();
  win.print();
}

export default function ReportContent() {
  const [product, setProduct] = useState<ProductAnalysis>(DEMO_PRODUCTS[1]);

  const handleExportPDF = useCallback(() => exportPDF(product), [product]);
  const handleExportText = useCallback(() => exportText(product), [product]);

  const scoreColor = product.qualityScore >= 85 ? 'text-pass' : product.qualityScore >= 70 ? 'text-review' : 'text-flag';
  const scoreBg = product.qualityScore >= 85 ? 'bg-pass/10' : product.qualityScore >= 70 ? 'bg-review/10' : 'bg-flag/10';

  return (
    <div className="max-w-screen-lg mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-accent/10 flex items-center justify-center">
            <FileText size={20} className="text-accent" />
          </div>
          <div>
            <h1 className="text-2xl font-extrabold text-navy">Compliance Report</h1>
            <p className="text-sm text-muted-foreground">AI-assisted inspection report</p>
          </div>
        </div>
        <div className="flex items-center gap-2 flex-wrap">
          <ProductSelector selected={product} onChange={setProduct} />
          <button
            onClick={handleExportText}
            className="flex items-center gap-1.5 px-4 py-2.5 rounded-xl border border-border bg-card text-sm font-medium text-muted-foreground hover:text-foreground hover:bg-muted transition-all"
          >
            <Edit3 size={14} />
            Export Editable TXT
          </button>
          <button
            onClick={handleExportPDF}
            className="btn-primary text-sm px-4 py-2.5"
          >
            <Download size={14} />
            Export PDF
          </button>
        </div>
      </div>

      {/* Product info + score */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="md:col-span-2 card p-5 space-y-3">
          <p className="text-xs font-bold text-muted-foreground uppercase tracking-wide">Product Information</p>
          <div className="grid grid-cols-2 gap-3">
            {[
              { label: 'Product Name', value: product.name },
              { label: 'Category', value: product.category },
              { label: 'Analyzed', value: product.analyzedAt },
              { label: 'Report ID', value: `LG-${product.id.toUpperCase().slice(-6)}` },
            ].map((row) => (
              <div key={row.label}>
                <p className="text-xs text-muted-foreground">{row.label}</p>
                <p className="text-sm font-semibold text-navy">{row.value}</p>
              </div>
            ))}
          </div>
        </div>
        <div className={`card p-5 flex flex-col items-center justify-center gap-2 ${scoreBg}`}>
          <p className="text-xs font-bold text-muted-foreground uppercase tracking-wide text-center">Compliance Screening Score</p>
          <p className={`text-5xl font-extrabold ${scoreColor}`}>{product.qualityScore}</p>
          <p className="text-sm text-muted-foreground">out of 100</p>
        </div>
      </div>

      {/* Score breakdown */}
      <div className="card p-5 space-y-4">
        <p className="text-sm font-bold text-navy">Score Breakdown</p>
        <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
          {[
            { label: 'Mandatory decl.', value: product.scoreBreakdown.mandatoryDeclarations },
            { label: 'Readability', value: product.scoreBreakdown.readability },
            { label: 'Confidence', value: product.scoreBreakdown.extractionConfidence },
            { label: 'Placement', value: product.scoreBreakdown.placementVisibility },
            { label: 'Consistency', value: product.scoreBreakdown.labelConsistency },
          ].map((item) => (
            <div key={item.label} className="text-center space-y-1.5">
              <div className="relative w-12 h-12 mx-auto">
                <svg viewBox="0 0 44 44" className="w-12 h-12 -rotate-90">
                  <circle cx="22" cy="22" r="18" fill="none" stroke="#e5e7eb" strokeWidth="4" />
                  <circle
                    cx="22" cy="22" r="18" fill="none"
                    stroke={item.value >= 85 ? '#22c55e' : item.value >= 70 ? '#f59e0b' : '#ef4444'}
                    strokeWidth="4"
                    strokeDasharray={`${(item.value / 100) * 113} 113`}
                    strokeLinecap="round"
                  />
                </svg>
                <span className="absolute inset-0 flex items-center justify-center text-xs font-bold text-navy">{item.value}</span>
              </div>
              <p className="text-xs text-muted-foreground">{item.label}</p>
            </div>
          ))}
        </div>
        <p className="text-xs text-muted-foreground/70 italic text-center flex items-center justify-center gap-1">
          <Info size={10} />
          AI-assisted screening — not an official legal certification.
        </p>
      </div>

      {/* Summary */}
      <div className="grid grid-cols-3 gap-3">
        <div className="card p-4 text-center border-pass/30">
          <CheckCircle2 size={20} className="text-pass mx-auto mb-1" />
          <p className="text-2xl font-extrabold text-pass">{product.passCount}</p>
          <p className="text-xs text-muted-foreground">PASS</p>
        </div>
        <div className="card p-4 text-center border-review/30">
          <AlertCircle size={20} className="text-review mx-auto mb-1" />
          <p className="text-2xl font-extrabold text-review">{product.reviewCount}</p>
          <p className="text-xs text-muted-foreground">REVIEW</p>
        </div>
        <div className="card p-4 text-center border-flag/30">
          <XCircle size={20} className="text-flag mx-auto mb-1" />
          <p className="text-2xl font-extrabold text-flag">{product.flagCount}</p>
          <p className="text-xs text-muted-foreground">FLAG</p>
        </div>
      </div>

      {/* Declaration table */}
      <div className="card overflow-hidden">
        <div className="px-5 py-4 border-b border-border">
          <h2 className="text-sm font-bold text-navy">Declaration Table</h2>
          <p className="text-xs text-muted-foreground mt-0.5">Extracted values, confidence, and compliance status</p>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="bg-muted/50 border-b border-border">
                <th className="text-left px-5 py-3 text-xs font-bold text-muted-foreground uppercase tracking-wide">Field</th>
                <th className="text-left px-5 py-3 text-xs font-bold text-muted-foreground uppercase tracking-wide">Detected Value</th>
                <th className="text-center px-4 py-3 text-xs font-bold text-muted-foreground uppercase tracking-wide">Confidence</th>
                <th className="text-center px-4 py-3 text-xs font-bold text-muted-foreground uppercase tracking-wide">Readability</th>
                <th className="text-center px-4 py-3 text-xs font-bold text-muted-foreground uppercase tracking-wide">Status</th>
              </tr>
            </thead>
            <tbody>
              {product.declarations.map((decl: Declaration, i: number) => (
                <tr key={decl.id} className={`border-b border-border last:border-0 ${i % 2 === 0 ? '' : 'bg-muted/20'}`}>
                  <td className="px-5 py-3 font-medium text-navy">{decl.field}</td>
                  <td className="px-5 py-3 text-muted-foreground max-w-[200px] truncate font-mono text-xs">{decl.extractedText || decl.value}</td>
                  <td className="px-4 py-3 text-center">
                    <span className={`text-xs font-semibold ${decl.confidence >= 80 ? 'text-pass' : decl.confidence >= 60 ? 'text-review' : 'text-flag'}`}>
                      {decl.confidence}%
                    </span>
                  </td>
                  <td className="px-4 py-3 text-center">
                    <span className={`text-xs font-semibold ${decl.readabilityLabel === 'GOOD' ? 'text-pass' : decl.readabilityLabel === 'ACCEPTABLE' ? 'text-review' : 'text-flag'}`}>
                      {decl.readabilityPx}px · {decl.readabilityLabel}
                    </span>
                  </td>
                  <td className="px-4 py-3 text-center">
                    <StatusBadge status={decl.status} />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Findings */}
      {product.findings.length > 0 && (
        <div className="card overflow-hidden">
          <div className="px-5 py-4 border-b border-border">
            <h2 className="text-sm font-bold text-navy">Findings & Evidence</h2>
            <p className="text-xs text-muted-foreground mt-0.5">Each finding links to extracted text and the compliance check that triggered it</p>
          </div>
          <div className="divide-y divide-border">
            {product.findings.map((finding: Finding) => (
              <div key={finding.id} className="px-5 py-4 space-y-3">
                <div className="flex items-start justify-between gap-3">
                  <p className="text-sm font-semibold text-navy">{finding.title}</p>
                  <StatusBadge status={finding.severity} />
                </div>

                {/* Evidence chain */}
                <div className="grid grid-cols-2 gap-2">
                  <div className="p-2.5 rounded-lg bg-muted/50">
                    <p className="text-xs text-muted-foreground mb-0.5">Detected Text</p>
                    <p className="text-xs font-mono font-medium text-navy">{finding.detectedText}</p>
                  </div>
                  <div className="p-2.5 rounded-lg bg-muted/50">
                    <p className="text-xs text-muted-foreground mb-0.5">Confidence</p>
                    <p className={`text-xs font-bold ${finding.confidence >= 80 ? 'text-pass' : finding.confidence >= 60 ? 'text-review' : 'text-flag'}`}>
                      {finding.confidence}%
                    </p>
                  </div>
                  <div className="p-2.5 rounded-lg bg-muted/50">
                    <p className="text-xs text-muted-foreground mb-0.5">Evidence Region</p>
                    <p className="text-xs font-medium text-navy">{finding.evidenceRegion}</p>
                  </div>
                  <div className="p-2.5 rounded-lg bg-muted/50">
                    <p className="text-xs text-muted-foreground mb-0.5">Compliance Check</p>
                    <p className="text-xs font-mono font-medium text-navy">{finding.ruleCheck}</p>
                  </div>
                </div>

                <p className="text-xs text-muted-foreground leading-relaxed">{finding.explanation}</p>

                <div className="flex items-start gap-1.5 p-2.5 rounded-lg bg-accent/5 border border-accent/20">
                  <Info size={12} className="text-accent mt-0.5 flex-shrink-0" />
                  <p className="text-xs text-accent leading-relaxed">{finding.recommendation}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Recommended actions */}
      {product.findings.length > 0 && (
        <div className="card p-5 space-y-3">
          <h2 className="text-sm font-bold text-navy">Recommended Actions</h2>
          <ul className="space-y-2">
            {product.findings.map((f: Finding) => (
              <li key={`action-${f.id}`} className="flex items-start gap-2 text-sm text-muted-foreground">
                <span className={`mt-1 w-1.5 h-1.5 rounded-full flex-shrink-0 ${f.severity === 'FLAG' ? 'bg-flag' : 'bg-review'}`} />
                {f.recommendation}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Disclaimer */}
      <div className="card p-5 border-amber-200 bg-amber-50 space-y-2">
        <div className="flex items-center gap-2">
          <Shield size={16} className="text-review" />
          <p className="text-sm font-bold text-amber-900">Disclaimer</p>
        </div>
        <p className="text-xs text-amber-800 leading-relaxed">
          This report is generated by LabelGuard AI and is intended for informational and screening purposes only.
          It does not constitute legal certification, official compliance verification, or a substitute for inspection
          by a qualified authority. All findings are AI-assisted and require manual verification. Confidence values
          and readability estimates are approximations. AI-assisted screening — not an official legal certification.
          LabelGuard AI assumes no legal liability for decisions made based on this report.
        </p>
      </div>
    </div>
  );
}
